Add functions for internal types
rinq/rinq-go pull request #130
Opened 2017-09-29 04:17 UTC by koden-km

Fixes #29

I'm not sure if all these were needed. Let me know and i'll update the changes.

2017-10-01 00:55 UTC, jmalloc commented
FYI @koden-km, I messed up your PR when I merged #126 -- we can go through these some time next week if you like, or I can cherry pick them out if you can't be bothered rebasing.

2017-10-03 02:47 UTC, koden-km commented
I have updated from master and fixed the merge conflicts.

2017-10-03 03:03 UTC, jmalloc requested changes

2017-10-03 03:03 UTC, jmalloc commented on src/rinq/internal/localsession/revision.go
> +func newRevision(
As discussed, this should probs just be "positional-inline-construction".

2017-10-03 03:03 UTC, jmalloc commented on src/rinq/internal/remotesession/revision.go
> +func newRevision(ref ident.Ref, cat *catalog) rinq.Revision {
Another positional one.

2017-10-03 07:00 UTC, jmalloc approved these changes

2017-10-03 07:00 UTC, merged