Include Rinq's traceID in opentracing span tags.
rinq/rinq-go pull request #160
Opened 2017-10-31 23:51 UTC by koden-km

Fixes #128

2017-11-01 00:20 UTC, jmalloc submitted a review, later dismissed
There are several other places where this change needs to be made.

Firstly, look for other uses of `command.Invoker` and `command.Notifier`.  There's probably no others for the notifier, but the command invoker and server are both used in the `remotesession` package for the `_sess` namespace, and also use perform tracing ops.

Finally, there's also some tracing performed on the "destination" end for both notifications and commands, which if I remember correctly is performed inside a closure in `localsession.Session.Listen` and `localsession.Session.SetAsyncHandler()`, respectively.

2017-11-01 00:20 UTC, jmalloc commented on src/internal/opentr/common.go
> +func AddTraceID(s opentracing.Span, id string) {
Please add tests for this function.

2017-11-01 05:32 UTC, koden-km commented
I'm not sure how to get a `traceID` in local session SetAsyncHandler?
`src/internal/localsession.session.go`
`func (s *Session) SetAsyncHandler(h rinq.AsyncHandler) error {`

2017-11-01 05:50 UTC, koden-km commented
I'm not sure about adding the trace to the span for notifier here:
`src/rinqamqp/internal/notifyamqp/notifier.go`
`func (n *notifier) NotifyUnicast(` and `func (n *notifier) NotifyMulticast(`.

I don't have the span it gets packed?

2017-11-01 08:41 UTC, jmalloc commented
> I'm not sure how to get a traceID in local session SetAsyncHandler?

The closure inside is passed a `ctx`, which is guaranteed to contain the trace ID by that point, so you can fetch it with `trace.Get(ctx)`.

2017-11-01 08:42 UTC, jmalloc commented
> I'm not sure about adding the trace to the span for notifier here:
> src/rinqamqp/internal/notifyamqp/notifier.go
> func (n *notifier) NotifyUnicast( and func (n *notifier) NotifyMulticast(.

I don't think you'll need to because the methods of `localsession.Session` that use these will have already done it.

2017-11-01 11:11 UTC, koden-km commented
OK I have added the trace id to the `SetAsyncHandler` using `trace.Get(ctx)`.
I checked the NotifyXxx methods and you are correct, they already have the trace set earlier in the Session.
I think that is all of those covered now.

I wasn't sure whether to add the extra blank line of spacing for those calls to `opentr.AddTraceID()`. I just tried to match the existing style and there seemed to be a blank line before the error check lines. I can remove that extra blank line if you prefer them packed tighter?

2017-11-01 21:44 UTC, jmalloc commented
> I can remove that extra blank line if you prefer them packed tighter?

I am trying to care less about this kind of trivial stuff.  If you run `make prepare` and it doesn't change it, then it's good!

2017-11-02 02:35 UTC, jmalloc reviewed
Trying review comment without approving or requesting changes.

2017-11-02 02:35 UTC, jmalloc submitted a review, later dismissed
Requesting changes.

2017-11-02 22:04 UTC, jmalloc requested changes
There are a few more places that need to have the trace ID added to the span:

- `rinqamqp.peer.Listen()` has a closure similar to `Session.SetAsyncHandler()`
- `remotesession.server` also creates spans

I *think* if you look for everywhere that `opentr.Setup<something>()` is called that will identify all the locations.

2017-11-02 22:12 UTC, koden-km commented
OK I will fix those up now.

2017-11-06 04:57 UTC, jmalloc commented
Before I merge this, I'd like for you to spin up Jaeger under Docker and try out each of these scenarios.

http://jaeger.readthedocs.io/en/latest/getting_started/#all-in-one-docker-image

There's no Rinq environment variable for configuring OpenTracing, so you'll need to configure the client yourself.

This is the client we use for Jaeger: https://github.com/jaegertracing/jaeger-client-go

That Jaeger client is just one possible implementation of the opentracing interfaces that Rinq uses.

2018-02-01 01:36 UTC, merged